# Generated by Django 4.0.5 on 2022-06-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="*Ім'я автора")),
                ('birthdate', models.DateField(blank=True, verbose_name='Дата народження')),
                ('death_date', models.DateField(blank=True, verbose_name='Дата смерті')),
                ('biography', models.TextField(blank=True, verbose_name='Біографія')),
                ('photo', models.ImageField(blank=True, upload_to='img', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='*Серія книг')),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='*Ілюстратор')),
            ],
        ),
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='*Перекладач')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='*Назва видавництва')),
                ('photo', models.ImageField(upload_to='img', verbose_name='*Фото')),
                ('info', models.TextField(verbose_name='*Опис видавництва')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='bookshop.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='*Назва підкатегорії'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField(blank=True, verbose_name='Тираж')),
                ('weight', models.IntegerField(blank=True, verbose_name='Вага')),
                ('first_publication_year', models.IntegerField(blank=True, verbose_name='Рік першого видання')),
                ('price', models.IntegerField(verbose_name='*Ціна')),
                ('publication_year', models.IntegerField(verbose_name='*Рік видання')),
                ('page_count', models.IntegerField(verbose_name='*Кількість сторінок')),
                ('language', models.CharField(choices=[('українська', 'Українська'), ('російська', 'Російська'), ('англійська', 'Англійська')], max_length=15, verbose_name='*Мова')),
                ('palette', models.CharField(choices=[('тверда', 'Тверда'), ("м'яка", "М'яка")], max_length=30, verbose_name='*Палітурка')),
                ('paper', models.CharField(choices=[('офсетний', 'Офсетний'), ('мелований', 'Мелований')], max_length=30, verbose_name='*Папір')),
                ('Illustrations', models.CharField(blank=True, choices=[('чорно-білі', 'Чорно-білі'), ('багатокольорові', 'Багатокольорові'), ('без зображень', 'Без зображень')], max_length=25, verbose_name='Ілюстрації')),
                ('book_type', models.CharField(choices=[('паперова', 'Паперова'), ('електронна', 'Електронна')], max_length=30, verbose_name='Тип')),
                ('format', models.CharField(max_length=100, verbose_name='*Формат книги (приклад: 145х215 мм)')),
                ('isbn', models.CharField(max_length=25, verbose_name='*isbn')),
                ('code_product', models.CharField(max_length=9, verbose_name='*Код товару')),
                ('cover_photo', models.ImageField(upload_to='img', verbose_name='Фото')),
                ('author', models.ManyToManyField(blank=True, default='Не обрано', to='bookshop.author', verbose_name='Автор')),
                ('book_series', models.ForeignKey(blank=True, default='Не обрано', on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop.bookseries', verbose_name='Серія книг')),
                ('category', models.ForeignKey(blank=True, default='Не обрано', on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop.subcategory', verbose_name='Категорія')),
                ('illustrator', models.ManyToManyField(blank=True, default='Не обрано', to='bookshop.illustrator', verbose_name='Ілюстратор')),
                ('interpreter', models.ManyToManyField(blank=True, default='Не обрано', to='bookshop.interpreter', verbose_name='Перекладач')),
                ('publisher', models.ForeignKey(default='Не обрано', on_delete=django.db.models.deletion.SET_DEFAULT, to='bookshop.publisher', verbose_name='*Видавництво')),
            ],
        ),
    ]
