# Generated by Django 4.0.5 on 2022-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_alter_author_biography_alter_author_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Illustrations',
            field=models.CharField(blank=True, choices=[('чорно-білі', 'Чорно-білі'), ('багатокольорові', 'Багатокольорові'), ('без зображень', 'Без зображень')], max_length=25, null=True, verbose_name='Ілюстрації'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('паперова', 'Паперова'), ('електронна', 'Електронна')], max_length=30, verbose_name='*Тип'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_publication_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рік першого видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вага'),
        ),
    ]
