# Generated by Django 4.0.5 on 2022-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_book_illustrations_alter_book_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва книги'),
        ),
    ]
