# Generated by Django 4.0.5 on 2022-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_items', models.TextField()),
                ('mail', models.CharField(max_length=100, verbose_name='Електронна пошта')),
                ('city', models.CharField(max_length=100, verbose_name='Місто доставки')),
                ('post_department', models.CharField(max_length=150, verbose_name='Поштове відділення(номер, адреса)')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Номер телефона')),
                ('status_success', models.BooleanField(null=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(upload_to='img', verbose_name='*Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='*Назва книги'),
        ),
    ]
