# Generated by Django 4.0.5 on 2022-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_customerorder_alter_book_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Усе про книжку'),
        ),
    ]
