# Generated by Django 4.0.5 on 2022-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0012_customerorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
