# Generated by Django 4.0.6 on 2022-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0013_customerorder_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=2500, verbose_name='Рецензія'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'Жахливо'), ('2', 'Погано'), ('3', 'Середньо'), ('4', 'Добре'), ('5', 'Чудово')], max_length=100, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
