# Generated by Django 4.0.6 on 2022-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0014_alter_review_options_review_date_alter_review_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
